name = "moneyDivider"
version = "0.1.0"
license = "BSD"
author = "Arttu R채s채nen"
maintainer = "<firstname>.<surname>(at)protonmail.com"
copyright = "Copyright 2021, Arttu R채s채nen"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
